### ISSUE TITLE
occ libresign:install --cli not working

### ISSUE THREAD

**Issue by kmorber** [LibreSign/libresign#1143]
When i issue this mentioned command, i receive the following error message:

An unhandled exception has been thrown:
TypeError: preg_match() expects parameter 2 to be string, bool given in /var/www/html/nextcloud/apps/libresign/lib/Service/InstallService.php:508
Stack trace:
#0 /var/www/html/nextcloud/apps/libresign/lib/Service/InstallService.php(508): preg_match('/(?<hash>\\w*) +...', false, NULL)
#1 /var/www/html/nextcloud/apps/libresign/lib/Service/InstallService.php(320): OCA\Libresign\Service\InstallService->getHash(Object(OC\Files\Node\Folder), 'libresign-cli', 'libresign_0.0.4...', '0.0.4', 'https://github....')
#2 /var/www/html/nextcloud/apps/libresign/lib/Command/Install.php(69): OCA\Libresign\Service\InstallService->installCli()
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Libresign\Command\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Libresign\Command\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#10 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')

What am i missing?

Best regards

Karsten

**Comment by kmorber** [comment]
Fixed by downloading the checksum files from github and rename them as shown in nextcloud log error message.
