### ISSUE TITLE
"Unknown Error" when signing a document

### ISSUE THREAD

**Issue by tonytonyistony** [LibreSign/libresign#1302]
**Describe the bug**
After entering the password to sign a document and "Unknown Error" occurs

**To Reproduce**
- User1 goes to files to select a PDF and issue a signature request to another Nextcloud user to their email.
- User2 receives an email and opens the request in Nextcloud. 
- User2 hits the "Sign the document" button and enters their password.
- After a couple seconds and error pops up stating "Unknown Error"

**Expected behavior**
PDF becomes signed.

**Screenshots**
![LibreSign01](https://user-images.githubusercontent.com/53504611/208990524-a30324c1-aec1-4f16-8916-a1009e62400f.png)
![LibreSign02](https://user-images.githubusercontent.com/53504611/208989354-971a0f42-f55b-47c7-96bd-5ab01ab89475.png)
![LibreSign03](https://user-images.githubusercontent.com/53504611/208989492-2469a479-2e77-4671-8622-e9e5046b653a.png)

**Environment information (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Browser: Vivaldi & Firefox
 - LibreSign Version: 6.2.2
 - Nextcloud Server Version: Nextcloud Hub 3 25.0.2
 - Logs:
 **Nextcloud.log**
None
**Apache Error Log**
I think this error was produced at the time of the root CA creation. Will try to reproduce.
```
[Wed Dec 21 00:00:03.150311 2022] [mpm_prefork:notice] [pid 1121] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Wed Dec 21 00:00:03.150350 2022] [core:notice] [pid 1121] AH00094: Command line: '/usr/sbin/apache2'
FINE Default property file doesn't exists.
FINE Default property file doesn't exists.
INFO Checking input and output PDF paths.
java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:650)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at net.sf.jsignpdf.utils.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:359)
	at net.sf.jsignpdf.utils.KeyStoreUtils.getPkInfo(KeyStoreUtils.java:411)
	at net.sf.jsignpdf.SignerLogic.signFile(SignerLogic.java:154)
	at net.sf.jsignpdf.Signer.signFiles(Signer.java:246)
	at net.sf.jsignpdf.Signer.main(Signer.java:139)
WARNING Keystore was not loaded succesfully. Check if the keystore type, path and password are valid.
SEVERE Problem occured
java.lang.NullPointerException: Keystore was not loaded succesfully. Check if the keystore type, path and password are valid.
	at net.sf.jsignpdf.utils.KeyStoreUtils.getKeyAliasInternal(KeyStoreUtils.java:224)
	at net.sf.jsignpdf.utils.KeyStoreUtils.getPkInfo(KeyStoreUtils.java:413)
	at net.sf.jsignpdf.SignerLogic.signFile(SignerLogic.java:154)
	at net.sf.jsignpdf.Signer.signFiles(Signer.java:246)
	at net.sf.jsignpdf.Signer.main(Signer.java:139)

INFO Finished: Creating of signature failed.
2022/12/21 06:54:52 [INFO] generate received request
2022/12/21 06:54:52 [INFO] received CSR
2022/12/21 06:54:52 [INFO] generating key: rsa-2048
2022/12/21 06:54:52 [INFO] encoded CSR
2022/12/21 06:54:52 [INFO] signed certificate with serial number 723990244453174423603685911283141029726118982312
FINE Default property file doesn't exists.
FINE Default property file doesn't exists.
INFO Checking input and output PDF paths.
java.io.IOException: Invalid keystore format
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:650)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:55)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at net.sf.jsignpdf.utils.KeyStoreUtils.loadKeyStore(KeyStoreUtils.java:359)
	at net.sf.jsignpdf.utils.KeyStoreUtils.getPkInfo(KeyStoreUtils.java:411)
	at net.sf.jsignpdf.SignerLogic.signFile(SignerLogic.java:154)
	at net.sf.jsignpdf.Signer.signFiles(Signer.java:246)
	at net.sf.jsignpdf.Signer.main(Signer.java:139)
WARNING Keystore was not loaded succesfully. Check if the keystore type, path and password are valid.
SEVERE Problem occured
java.lang.NullPointerException: Keystore was not loaded succesfully. Check if the keystore type, path and password are valid.
	at net.sf.jsignpdf.utils.KeyStoreUtils.getKeyAliasInternal(KeyStoreUtils.java:224)
	at net.sf.jsignpdf.utils.KeyStoreUtils.getPkInfo(KeyStoreUtils.java:413)
	at net.sf.jsignpdf.SignerLogic.signFile(SignerLogic.java:154)
	at net.sf.jsignpdf.Signer.signFiles(Signer.java:246)
	at net.sf.jsignpdf.Signer.main(Signer.java:139)

INFO Finished: Creating of signature failed.
```

**Additional context**
My Nextcloud instance works out of an attached NFS share. I noticed that the libresign-cli uses a path inside this mount point. Its possible there is a permission issue happening. Ive seen issues with Nextcloud and its updater using the NAS to handle updates and permissions.

Are there any firewall port forwarding requirements?

**Comment by tonytonyistony** [comment]
I have resolved the issue by reissuing the root CA cert.

After viewing the Apache error logs and seeing the errors it prompted me to do this. After the reissue, the Apache log looked clean, then I followed the reproduction steps above and the file was signed successfully.

```
user@*****:/var/www/nextcloud/apps/libresign/appinfo$ tail -f -n 0 /var/log/apache2/error.log
2022/12/21 22:14:32 [INFO] generate received request
2022/12/21 22:14:32 [INFO] received CSR
2022/12/21 22:14:32 [INFO] generating key: rsa-2048
2022/12/21 22:14:32 [INFO] encoded CSR
2022/12/21 22:14:32 [INFO] signed certificate with serial number 180303067797277270849612325239971875482018901518
```

**Comment by tonytonyistony** [comment]
Reopening...
It only works when the admin account signs the document, when the admin sends a signature to a non admin the Unknown Error occurs.

**Comment by tonytonyistony** [comment]
I have successfully bricked my install trying to completely uninstall this app. Libresign is no longer functional on my nextcloud at all. I will be opening a new ticket to troubleshoot what Ive done to this thing.

**Comment by vitormattos** [comment]
Only to inform to other person that could come here:

Looking the new issue, #1303, sounds that this problem occur because LibreSign tried to get files that exists on cache but not exists on filesystem because was deleted directly from filesystem.

Running the scan on app-data folder could solve this problem and running after the install and check command will be possible identify what happening.
```
occ files:scan-app-data libresign
occ libresign:install
occ libresign:configure:check
```
