### ISSUE TITLE
No way to sign when footer is activated

### ISSUE THREAD

**Issue by MaitreCake** [LibreSign/libresign#4223]
Hi there, 

Firstly, thanks for the great job you are doing. I follow the project for a while now and try to make it work on my installation every 6 to 9 months. And I am close to realize it.

Indeed, it does work on my shared hosting server OVH ( Nextcloud Hub 9 (30.0.4) / LibreSign 10.4.4)
![image](https://github.com/user-attachments/assets/583441bd-c0a2-4e9d-8e89-90139c8ef6e6)

However, when I want to activate the footer, if I click sign or confirm, the spinner stays for ages and nothing happens…
![image](https://github.com/user-attachments/assets/8c28d081-18e6-4f5d-b495-87c8e254d643)

As said, I am hosted on a shared server, I did not find any access to a specific php log, however the mention :
`Script timed out before returning headers: v2.php` looks like appearing when I face the problem.

The mention of server overload makes me think it may have something to do with :  [Signature Areas not defined -> Leading to Server Overload and Errors #4104](https://github.com/LibreSign/libresign/issues/4104) but @blackerking did not provide more clues about it.

The only mention in NC logs of LibreSign was an `"ExApp "libresign" not found.` . This is not relevant anymore since I disabled the AppAPI app.

I did try to reinstall several times the app, cleaning the setting by OCC commands, deleting the libresign folders too but without cleaning the DB. That is may be way at every "new" install, the docs I requested a signature for came back. 

I did try with unusual and A4 paper sizes too

For the use I want to have of the app, a time stamp next to the signature would be enough for me, however if you could help I would be delighted.

I stay of course at your disposal, 

Regards, 

PHP 8.2.21 /  mysql Version : 8.0.39

**Comment by vitormattos** [comment]
> However, when I want to activate the footer, if I click sign or confirm, the spinner stays for ages and nothing happens…

Could you check the developer tools of your browser when you click at "Confirmer" ? And also, check the nextcloud.log file at this moment.

If haven't any sensible data, could you provide the PDF file that you are using? Maybe is a problem related to version of PDF. PDF-2 isn't full supported.

> As said, I am hosted on a shared server, I did not find any access to a specific php log, however the mention

You can get the logs from nextcloud.log file or going to `Administration settings` > `Logging`

> The only mention in NC logs of LibreSign was an "ExApp "libresign" not found. . This is not relevant anymore since I disabled the AppAPI app.

Where did you got this?

**Comment by MaitreCake** [comment]
Thank you for your fast reply

**1. Dev Tools**
 About the developer tools, I am a kind of noob, but with Firefox nothing happens in the console when I click on **"Confirm"**. After a while if I refresh the page  this is coming in the console :

 
> TypeError: e.response is undefined
>     signDocument Sign.vue:180
>     promise callback*signDocument Sign.vue:179
>     signWithClick Sign.vue:133
>     VueJS 4
>         fn
>         n
>         fn
>         $emit
>     click NcButton.mjs:231
>     VueJS 33
>         fn
>         n
>         _wrapper
>         Ra
>         _t
>         za
>         v
>         h
>         Ei
>         _update
>         r
>         get
>         e
>         mount
>         $mount
>         init
>         h
>         h
>         f
>         h
>         f
>         h
>         f
>         h
>         f
>         h
>         f
>         h
>         Ei
>         _update
>         r
>         get
>         e
> libresign-main.js:2:3750104
>     vn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     gn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     pn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     fn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     (Asynchrone : promise callback)
>     fn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     n https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     fn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     $emit https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     click https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     fn https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     n https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     _wrapper https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     (Asynchrone : EventListener.handleEvent)
>     Ra https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     _t https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     za https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     v https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     Ei https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     _update https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     r https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     get https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     e https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     mount https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     $mount https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     init https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     f https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     f https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     f https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     f https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     f https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     h https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     Ei https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     _update https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     r https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     get https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2
>     e https://MYDOMAIN/apps/libresign/js/libresign-main.js?v=628043dc-19:2

I attach a long debug message thrown by the first exception `TypeError: Invalid type: first can't be a Regular Expression
`[Debugger.txt](https://github.com/user-attachments/files/18280257/Debugger.txt)

**2. PDF Versions**
I did try with several pdf, most of them are in 1.7 version. I add an example here 
[Location journalie-re -Interactive- reponse.pdf](https://github.com/user-attachments/files/18280277/Location.journalie-re.-Interactive-.reponse.pdf)

**3. NC log**
Well, as said, nothing happens in the NC log regarding LibreSign, except if I activate this app : [App_api](url) https://apps.nextcloud.com/apps/app_api and then this is coming when I click **confirm**
`[app_api] Déboguage: ExApp "libresign" not found.
	GET /ocs/v2.php/apps/notifications/api/v2/notifications
	de XX.XX.XXX.XXX par MaitreCake à 31 déc. 2024, 09:06:58
`
I stay of course available

**Comment by MaitreCake** [comment]
Hi, 

I realize that the PDF I gave as an example contains some form fields. I do have the issue with blank PDFs too.

Are the informations I gave you enough to solve the issue ?

All the best for 2025,

**Comment by vitormattos** [comment]
Could you provide all the steps that you made?
Will be necessary check all because I can't reproduce this issue.

- Get the settings from Administration Settings > LibreSign
- The flow that you made to request to sign
- The flow that you made to sign

If possible record your screen also will be very good.

**Comment by MaitreCake** [comment]
Hello, 

I am kind of busy nowadays (as you must be too), so recording my screen will have to wait for the week-end. 
However I did the upgrade to LibreSign 10.5.0, a `occ maintenance --off` then `occ libresign:install --all` had been necessary.

Blurring my sensitive data, I have realized that a `//` is seen in my config ?

![image](https://github.com/user-attachments/assets/5033d837-56ea-48d8-bbd7-aec5298f741e)



By the way, the behavior changed since the upgrade.

When I click "sign" on the pop-up window, the spinner comes to disappear for the pop-up to appear again : 

![image](https://github.com/user-attachments/assets/1cf7d1e0-39e2-4f3f-a8c9-3e37d58b84e6)

and I have the following log error coming :

Here is the result when I use the NC Copy/Paste tool : 
```
[PHP] Erreur: Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void at /home/LOCAL_ADDRESS/apps/libresign/vendor/mpdf/psr-log-aware-trait/src/MpdfPsrLogAwareTrait.php#15
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/e8c8cbc9-f74f-4ea5-9489-14d85fe39b74
	de 82.XX.XXX.XXX par MaitreCake à 14 janv. 2025, 23:56:52
```
Just in case, here is a manual copy (I spotted on the screen some "`\\`") 
`
"Declaration of Mpdf\\Mpdf::setLogger(Psr\\Log\\LoggerInterface $logger) must be compatible with Psr\\Log\\LoggerAwareInterface::setLogger(Psr\\Log\\LoggerInterface $logger): void at /home/LOCAL_ADDRESS/apps/libresign/vendor/mpdf/psr-log-aware-trait/src/MpdfPsrLogAwareTrait.php#15",
`
_LOCAL_ADDRESS was added by hand instead of the proper directory_

FYI : It happens by email token or click request.

Thanks again, 

If not enough I will dig up ASAP recording my screen as requested

**Comment by vitormattos** [comment]
> Blurring my sensitive data, I have realized that a // is seen in my config ?

This isn't a problem. You can ignore this.

**Comment by vitormattos** [comment]
Could you test again at newest release?

**Comment by vitormattos** [comment]
I can't reproduce this issue but mPDF only is used when is added the footer at PDF files.

**Comment by vitormattos** [comment]
If possible, also would be good to have the PDF that you are using, maybe is a specific problem with your PDF file.

**Comment by MaitreCake** [comment]
As said I did try with several Pdf V1.7 most of them exported from LibreOffice (uploaded by the app or already in some NC folders), but downladed randoms ones too .

I guess the issue must come from my shared hoster (OVH) but difficult to say from where.

By the way, with LibreSign 10.5.2 , the issue is still on with the same log coming from nextcloud : 

![Image](https://github.com/user-attachments/assets/535cc67f-9287-430f-8ecb-68f427531519)

It does the same when I want to add my signature on the doc without footer.

The log entry appears when I click `confirm` after `sign the document`. The confirmation pop up window shows a spinner and appears again... 

I 'll try to activate fpm later on. It is more or less the only setting I can play with on my server (It makes my theming look bad, but I'll give it a try). 

I keep you updated

**Comment by MaitreCake** [comment]
As promised, I keep you updated. 
- So FPM or CGI does not change anything.

However, here is how I reproduce the issue ⬇ 

1. I upload the doc (I have chosen here the simpliest of all)

[Thepdf.pdf](https://github.com/user-attachments/files/18445376/Thepdf.pdf)

2. I request the signature
   I add a signatory (here the current NC user)
   I click `next`
   
3. On the next windows, I click on the name of the current user in order to choose where the signature needs to appear. Then I click "`request`". A pop-up asks me if I really want to request a signature. I click `request`. A small square notification windows says "success"

4. The current user receives notifications telling him his signature is requested.

5. I go on LibreSign / Folder menu , I can see the pdf with an orange dot. I click on it then, on `sign`.

6. Another window appears, with a preview of the document  on the main panel and my set signature on the right panel.

▶ New but linked issue  :   If I try to change my signature from here , it does not work. The "save button" in the confirmation windows send me back to the previous pop up. However, If I delete it, and set another one it works. (The same happens if I want to do it from LibreSign/Parameters/My account )

Faulty windows : 

![Image](https://github.com/user-attachments/assets/c144cad8-aa27-47da-b472-2e6db88a8255)

The Nextcloud log mention the same error than previously mentionned on the thread

7. By the way, regarding the dev tools, a friend of mine told me to go on the network side. So, when I click on "confirm" for the signature , the error on the network tab   is 

`/ocs/v2.php/apps/libresign/api/v1/sign/uuid/9046a321-4566-48d7-8044-9ddeec16b0a0` going on 500

On the debogger side : axios.js : the line 40 

```

>  39     try {
>  40     return await this._request(configOrUrl, config);
>  41      } 
> 

```
is underlined in red with request highlighted. If I click on display the original variables, it is said that config in undefined...

![Image](https://github.com/user-attachments/assets/c34c2662-83a1-4b2e-bc1b-6a2a3bb6f74a)
  
The next and last exception is on line 61 `throw err`; with throw being highlighted but I haven't a clue why.

![Image](https://github.com/user-attachments/assets/ea26b419-769d-488f-b728-7547ad83928f)


Playing with the dev tools (With my knowledge and experience, I cannot do more than trying or playing),  I found another error :

> ab13/e.exports - spoofer.js:1:45450
> TypeError: Invalid type: first can't be a Regular Expression


I believe there are some clues here to move forward
I truly thank you for the spent time 🙏 👍 👏 . I would like to have more knowledge to help with.


_PS : (As noticed , all my set-up is in French, that's maybe why I did not use the proper name for some buttons. If you want me to change my config in English for you to better understand the screenshots, just let me know)_

**Comment by MaitreCake** [comment]
That was a fast reply.
I guessed that you coul not reproduce the issue.

Here is the list (my NC have been updated for ages from owncloud (at least 8 yo) : 

> Enabled:
>   - admin_audit: 1.20.0
>   - appointments: 2.3.5
>   - calendar: 5.0.9
>   - calendar_resource_management: 0.8.0
>   - cloud_federation_api: 1.13.0
>   - comments: 1.20.1
>   - contacts: 6.1.3
>   - contactsinteraction: 1.11.0
>   - dashboard: 7.10.0
>   - dav: 1.31.1
>   - deck: 1.14.3
>   - event_update_notification: 2.5.0
>   - federatedfilesharing: 1.20.0
>   - files: 2.2.0
>   - files_downloadlimit: 3.0.0
>   - files_external: 1.22.0
>   - files_pdfviewer: 3.0.0
>   - files_reminders: 1.3.0
>   - files_sharing: 1.22.0
>   - files_trashbin: 1.20.1
>   - files_versions: 1.23.0
>   - flow_notifications: 1.10.1
>   - forms: 4.3.5
>   - gpxpod: 7.0.4
>   - libresign: 10.5.2
>   - logreader: 3.0.0
>   - lookup_server_connector: 1.18.0
>   - mail: 4.1.1
>   - nextcloud_announcements: 2.0.0
>   - notes: 4.11.0
>   - notifications: 3.0.0
>   - oauth2: 1.18.1
>   - password_policy: 2.0.0
>   - photos: 3.0.2
>   - polls: 7.2.9
>   - privacy: 2.0.0
>   - provisioning_api: 1.20.0
>   - recommendations: 3.0.0
>   - related_resources: 1.5.0
>   - richdocuments: 8.5.3
>   - serverinfo: 2.0.0
>   - settings: 1.13.0
>   - spreed: 20.1.2
>   - support: 2.0.0
>   - survey_client: 2.0.0
>   - systemtags: 1.20.0
>   - tables: 0.8.3
>   - tasks: 0.16.1
>   - text: 4.1.0
>   - theming: 2.5.0
>   - thesearchpage: 1.2.8
>   - timemanager: 0.3.16
>   - twofactor_backupcodes: 1.19.0
>   - updatenotification: 1.20.0
>   - user_status: 1.10.0
>   - viewer: 3.0.0
>   - weather_status: 1.10.0
>   - webhook_listeners: 1.1.0-dev
>   - workflowengine: 2.12.0
> Disabled:
>   - activity: 3.0.0 (installed 2.4.2)
>   - app_api: 4.0.3 (installed 4.0.3)
>   - bruteforcesettings: 3.0.0 (installed 2.0.1)
>   - circles: 30.0.0 (installed 25.0.0)
>   - encryption: 2.18.0
>   - federation: 1.20.0 (installed 1.9.0)
>   - firstrunwizard: 3.0.0 (installed 1.1)
>   - sharebymail: 1.20.0 (installed 1.9.0)
>   - suspicious_login: 8.0.0
>   - twofactor_nextcloud_notification: 4.0.0
>   - twofactor_totp: 12.0.0-dev
>   - user_ldap: 1.21.0
>

**Comment by vitormattos** [comment]
I make tests at many servers with Nextcloud 30 and 29 and didn't reproduced this issue.

I think that is related to an app at your environment that is loading the `LoggerInterface` with an old definition of method `setLogger` The old definition of this method is:
```php
public function setLogger(LoggerInterface $logger);
```

The newest definition is:
```php
public function setLogger(LoggerInterface $logger): void;
```
Maybe sending here the return of this grep made at nextcloud folder could help to think what's could be the problem:
```
grep -Rn "function setLogger" --include="LoggerAwareInterface.php"
```

I identified that at Nextcloud <= 30 is using the oldest definition of this method, at Nextcloud 31 this already was changed but Nextcloud 31 istn't a stable release yet. I think that an app is loading this file at a middleware trigged before LibreSign.

Analyzing this case yet.

**Comment by MaitreCake** [comment]
So I did `grep -Rn "function setLogger" --include="LoggerAwareInterface.php"`

The result was 

> 3rdparty/psr/log/src/LoggerAwareInterface.php:17:    public function setLogger(LoggerInterface $logger);
> apps/suspicious_login/vendor/psr/log/Psr/Log/LoggerAwareInterface.php:17:    public function setLogger(LoggerInterface $logger);
> apps/mail/vendor/psr/log/src/LoggerAwareInterface.php:13:    public function setLogger(LoggerInterface $logger): void;
> apps/libresign/vendor/psr/log/src/LoggerAwareInterface.php:17:    public function setLogger(LoggerInterface $logger);
> apps/gpxpod/vendor/psr/log/src/LoggerAwareInterface.php:13:    public function setLogger(LoggerInterface $logger): void;

No void for Libresign
I desactivated suspicious_login, mail and gpxpod apps.

I gave a try and  the behavor change again. The "confirm signature" windows stays without closing like at the beginning of this thread and then : 
	`
Maximum execution time of 165 seconds exceeded at ROOTFOLDER/lib/private/Log/ErrorHandler.php#53 ` (NC log)

The debug said :
```71083/Xe.transformResponse< - libresign-main.js:2:4886387
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
I have too : 
"request - libresign-main.js:2:4903612"

It may have something to do with the cache of my share hoster.
I wonder if I would be better to wait for NC 31 ...

Thank you very much by the way

**Comment by vitormattos** [comment]
Could you test to change the follow row?

```
apps/libresign/vendor/psr/log/src/LoggerAwareInterface.php:17:    public function setLogger(LoggerInterface $logger);
```

Add `:void; ` at end of the row, like the other rows.

I think that is a problem at GitHub Action that generate the release.

**Comment by MaitreCake** [comment]
Hello @vitormattos, 

I did add `: void;` with a space to make it look like the other rows.
With or without space the result is the same.

No behavior change. Now the NC log says : 

>  Declaration of Sabre\DAV\Server::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void at /MYFOLDER/apps/libresign/vendor/psr/log/src/LoggerAwareTrait.php#22

Same without the extra space.

**Comment by vitormattos** [comment]
Ignore the previous message. At Nextcloud 30 the 3rdparty dependency need to be without `void` and all apps need to follow this and looking the source of LibreSign at stable30 branch (used to versions 10.x.x), the psr/log dependency are at the same version of 3rdparty.

I think that could be something related to APC cache because I reproduced this at a server that had the version 10.4.4 and I made the upgrade to 10.5.2. After then, to identify what's happening, I deleted the libresign folder, made a clone of repository, made the build and installed the composer dependencies, the error was solved. I deleted the folder that I made the clone and installed again from appstore and I can't reproduce the error again.

**Comment by vitormattos** [comment]
> ▶ New but linked issue : If I try to change my signature from here , it does not work. The "save button" in the confirmation windows send me back to the previous pop up. However, If I delete it, and set another one it works. (The same happens if I want to do it from LibreSign/Parameters/My account )

Fixed here: 

https://github.com/LibreSign/libresign/pull/4437

**Comment by vitormattos** [comment]
> /ocs/v2.php/apps/libresign/api/v1/sign/uuid/9046a321-4566-48d7-8044-9ddeec16b0a0 going on 500

Error 500 is error at server side and generate log, maybe at nextcloud.log or maybe at your HTTP server.

Could you check what's happening at server side when the error 500 is throw?

I reproduced the issue related to mpdf at an instance but after then the server was restarted, I couldn't do it again. I think that the error related to mpdf could be an APC cache.

**Comment by MaitreCake** [comment]
Well, it is quite difficult for me to find the proper log regarding the 500 error (OVH shared host...)

>▶ New but linked issue : If I try to change my signature from here , it does not work. The "save button" in the confirmation windows send me back to the previous pop up. However, If I delete it, and set another one it works. (The same happens if I want to do it from LibreSign/Parameters/My account ) 
Fixed here:
 https://github.com/LibreSign/libresign/pull/4437`

The update did not come to me yet (or not working). 

I will wait for the next NC upgrade (to 31), I let you informed about the main issue.
However I agree on the fact the issue must come from a misconfiguration of the cache, but, at the moment, I can do anything about it on my set-up.

Thanks again

**Comment by vitormattos** [comment]
> The update did not come to me yet (or not working).

I'm waiting to publish a new release.

**Comment by vitormattos** [comment]
Could you test with the newest release?

**Comment by MaitreCake** [comment]
I do my best to follow-up ASAP.

So the issue is still on with LiberSign

The spinner stays on and nothing happens, 
the log says : `Capabilities of OCA\\CloudFederationAPI\\Capabilities took 0.41 seconds to generate." ` , but no app in context...


> 
> ▶ New but linked issue : If I try to change my signature from here , it does not work. The "save button" in the confirmation windows send me back to the previous pop up. However, If I delete it, and set another one it works. (The same happens if I want to do it from LibreSign/Parameters/My account )
> 
> Fixed here:
> 
>     https://github.com/LibreSign/libresign/pull/4437

This pop up appears when I try to change the signature:  `"LibreSign/2025-01-16T20-32-43-067995_XXX/421432ff-84c4-48f9-a540-149f137527e0.png" is locked` .

**Comment by vitormattos** [comment]
Could you check if you have the app mail? If yes, could you test to disable this app and check if will solve the issue?

**Comment by vitormattos** [comment]
Your scenario is the same of this:
- https://github.com/LibreSign/libresign/issues/4376

**Comment by MaitreCake** [comment]
Mail app : I disabled it for the previous tests and did not reactive it. 

>  Your scenario is the same of this:
> 
> https://github.com/LibreSign/libresign/issues/4376

I do follow the thread as often as I can. But as said, I deactivated the mail app and the spinners stays on.

If I add a `:void` at the end of line 15 of `/apps/libresign/vendor/mpdf/psr-log-aware-trait/src /PsrLogAwareTrait.php`, the spinner disappears faster to display back to the confirmation pop-up. No log.

If I add a `:void;` with a `;` I do have the following log :

> During class fetch: Uncaught ParseError: syntax error, unexpected token \"{\", expecting \"function\" or \"const\" in NC_FOLDER/apps/libresign/vendor/mpdf/psr-log-aware-trait/src/PsrLogAwareTrait.php:16\nStack trace:\n#0 NC_FOLDER/lib/composer/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}('NC_FOLDER...')\n#1 NC_FOLDER/apps/libresign/vendor/mpdf/mpdf/src/SizeConverter.php(9): Composer\\Autoload\\ClassLoader->loadClass('Mpdf\\\\PsrLogAwar...')\n#2 NC_FOLDER/lib/composer/composer/ClassLoader.php(576): include('NC_FOLDER...')\n#3 NC_FOLDER/lib/composer/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}('NC_FOLDER...')\n#4 NC_FOLDER/apps/libresign/vendor/mpdf/mpdf/src/ServiceFactory.php(54): Composer\\Autoload\\ClassLoader->loadClass('Mpdf\\\\SizeConver...')\n#5 NC_FOLDER/apps/libresign/vendor/mpdf/mpdf/src/Mpdf.php(1075): Mpdf\\ServiceFactory->getServices(Object(Mpdf\\Mpdf), Object(Psr\\Log\\NullLogger), Array, Object(Mpdf\\Language\\LanguageToFont), Object(Mpdf\\Language\\ScriptToLanguage), NULL, NULL, NULL, NULL)\n#6 NC_FOLDER/apps/libresign/lib/Handler/FooterHandler.php(59): Mpdf\\Mpdf->__construct(Array)\n#7 NC_FOLDER/apps/libresign/lib/Service/SignFileService.php(543): OCA\\Libresign\\Handler\\FooterHandler->getFooter(Object(OC\\Files\\Node\\File), Object(OCA\\Libresign\\Db\\File))\n#8 NC_FOLDER/apps/libresign/lib/Service/SignFileService.php(396): OCA\\Libresign\\Service\\SignFileService->getPdfToSign(Object(OCA\\Libresign\\Db\\File), Object(OC\\Files\\Node\\File))\n#9 NC_FOLDER/apps/libresign/lib/Service/SignFileService.php(260): OCA\\Libresign\\Service\\SignFileService->getFileToSing(Object(OCA\\Libresign\\Db\\File))\n#10 NC_FOLDER/apps/libresign/lib/Controller/SignFileController.php(133): OCA\\Libresign\\Service\\SignFileService->sign()\n#11 NC_FOLDER/apps/libresign/lib/Controller/SignFileController.php(95): OCA\\Libresign\\Controller\\SignFileController->sign('clickToSign', Array, '', '', NULL, '9046a321-4566-4...')\n#12 NC_FOLDER/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\\Libresign\\Controller\\SignFileController->signUsingUuid('9046a321-4566-4...', 'clickToSign', Array, '', '')\n#13 NC_FOLDER/lib/private/AppFramework/Http/Dispatcher.php(114): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Libresign\\Controller\\SignFileController), 'signUsingUuid')\n#14 NC_FOLDER/lib/private/AppFramework/App.php(161): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Libresign\\Controller\\SignFileController), 'signUsingUuid')\n#15 NC_FOLDER/lib/private/Route/Router.php(302): OC\\AppFramework\\App::main('OCA\\\\Libresign\\\\C...', 'signUsingUuid', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#16 NC_FOLDER/ocs/v1.php(43): OC\\Route\\Router->match('/ocsapp/apps/li...')\n#17 NC_FOLDER/ocs/v2.php(7): require_once('NC_FOLDER...')\n#18 {main} at NC_FOLDER/apps/libresign/vendor/mpdf/mpdf/src/SizeConverter.php#9",

I guess there should not be a ';' there , I have not a clue of what to do but at least there is a list of every concerned files, just in case it may help.

**Comment by vitormattos** [comment]
As explained at #4376, the :void is the problem that app Mail is generating. The right way is without :void as is coming at vendor folder of LibreSign and at 3rdparty of server.

All dependencies need to use the same version o 3rdparty, and is possible to see the used versions with the follow command:
```bash
grep -Rn "function setLogger" --include="LoggerAwareInterface.php"
```

**Comment by MaitreCake** [comment]
It returns  that mail and the gpxpod apps use `:void`.
However, the two are deactivated on my NC.

Thx again, I am kind of waiting for the release of NC31 to see what will happen

**Comment by vitormattos** [comment]
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Comment by MaitreCake** [comment]
Congrats, it works like a charm with LibreSign 10.6.2.

I have to create some flows, to experiment it a bit more. 

Thanks a lot
