### ISSUE TITLE
Error during update Nextcloud 23.0.5

### ISSUE THREAD

**Issue by Iwios** [LibreSign/libresign#824]
When I try to update my Netxcloud 23.0.5 to  I have an error from Libresign update :

Updating <libresign> ...
An unhandled exception has been thrown:
Error: Call to a member function getAppValue() on null in cloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php:108
Stack trace:
#0 cloud/apps/libresign/lib/Migration/Version2040Date20211027183759.php(67): OCA\Libresign\Migration\Version2040Date20211027183759->getLibesignCli()
#1 cloud/lib/private/DB/MigrationService.php(547): OCA\Libresign\Migration\Version2040Date20211027183759->postSchemaChange()
#2 cloud/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep()
#3cloud/lib/private/legacy/OC_App.php(1021): OC\DB\MigrationService->migrate()
#4 cloud/lib/private/Updater.php(353): OC_App::updateApp()
#5 cloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#6 cloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#7 cloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#8 cloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 cloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 cloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 cloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 cloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#13 cloud/console.php(99): OC\Console\Application->run()
#14 cloud/occ(11): require_once('...')
#15 {main}

This bug blocke completly my Nextcloud upgrade.

To reproduce :+1: Nextcloud 23.0.5 installe
LibreSign V

Update Nextcloud to the next version (Same result with an update from Web or OCC cli)

**Comment by Iwios** [comment]
I've decide to completly remove the plugin and re-install the V4.1.1 from github repo.

That's work.
I don't know why the upgrade of Nextcloud was blocked by the plugin
